name: Dump TrickSurf API

on:
  schedule:
    - cron: 0 12 * * 2

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Update Script
        run: python src/main.py --dump-trick-surf

      - name: Git Config
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Git Add
        run: git add -A

      - name: Git Commit
        run: git commit -m "Update JSON dumps of TrickSurf API data"

      - name: Git Push
        run: git push origin main
